### ISSUE TITLE
ADDING BACK TO TOP BUTTON

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [notsoocool/codecache#101]
**Is your feature request related to a problem? Please describe.**
A back to top button needs to be added at the bottom of the page.

**Describe the solution you'd like**
A back to top button needs to be added at the bottom of the page for directly going to top after reaching the bottom of the page.

PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd  and level.

**Comment by notsoocool** [comment]
Sure go ahead.

**Comment by ABHISIKTAcommits** [comment]
sir please assign the issue
