### ISSUE TITLE
Designing a custom error 404 custom page 

### ISSUE THREAD

**Issue by dev129** [notsoocool/codecache#108]
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the `GSSOC-ext` and `Hacktoberfest` and `level` labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by notsoocool** [comment]
Hi @dev129,

Thanks for your proposal! Please go ahead with designing the custom 404 page. Just keep in mind to make the design sleek and minimalist, in line with our existing UI. 

Looking forward to seeing your design!

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/079d57f8-17a5-4655-8614-ffb7b307a586)
This is my design, after your approval shall I start designing.

**Comment by notsoocool** [comment]
Kindly show me the final design, I like the theming and ui so just update it with wordings and picture

**Comment by dev129** [comment]
Are you still up @notsoocool ?

**Comment by notsoocool** [comment]
@dev129 yes go ahead.
