### ISSUE TITLE
Addition of a Dockerfile

### ISSUE THREAD

**Issue by unknown91tech** [notsoocool/codecache#112]
@notsoocool Addition of the docker file will help in smoother running of the project locally.

**Comment by notsoocool** [comment]
@unknown91tech go ahead, i am assigning you this issue.

**Comment by notsoocool** [comment]
@unknown91tech any updates

**Comment by unknown91tech** [comment]
yes will create a pr by tomorrow

**Comment by unknown91tech** [comment]
@notsoocool created a pr can you check the pr
