### ISSUE TITLE
UI Improvement in Home Page

### ISSUE THREAD

**Issue by Bhum-ika** [notsoocool/codecache#115]
**Is your feature request related to a problem? Please describe.**
The Home page is not attractive , info should be present in an easily readable format

**Describe the solution you'd like**
The key features of the project can be presented in the form of cards rather than a bullet list. An image can be added to the front page to demonstrate the entire website. This will be accompanied by complete documentation, allowing us to make necessary changes to enhance its attractiveness and improve the user experience.

**Describe alternatives you've considered**
A bit of framer motion can be used

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by notsoocool** [comment]
@Bhum-ika Sure, go ahead with the improvements, but please ensure the UI remains sleek and minimalist, consistent with our current design. Also, make sure to fetch the latest changes from the `develop` branch and push your changes to the `develop` branch only. Looking forward to seeing your updates!

**Comment by Bhum-ika** [comment]
Suree
