### ISSUE TITLE
Addition of ProgressBar | That will shows the Current Depth of the webpage 

### ISSUE THREAD

**Issue by Shariq2003** [notsoocool/codecache#122]
I want to implement the progressBar into the website that will shows the Current Depth of the webpage.
Just like in GSSOC Website

![image](https://github.com/user-attachments/assets/acdcc4a1-e981-4076-a36b-250b2ad8a412)

Look at the Top, an orange line.

**Comment by notsoocool** [comment]
@Shariq2003 sure go ahead but keep in mind to make it minimalist and sleek.

**Comment by Gauravtb2253** [comment]
Pls assign me
