### ISSUE TITLE
Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [notsoocool/codecache#124]
**Is your feature request related to a problem? Please describe.**
Currently there is no input validation present in the login and signup form

**Describe the solution you'd like**
I would like to add proper validation so that valid data is sent to backend

**Comment by notsoocool** [comment]
@Gauravtb2253 We are currently using Clerk for handling the login and signup processes, which already includes input validation. If you have any suggestions for additional validations or improvements, feel free to discuss them!

**Comment by Gauravtb2253** [comment]
Do you have any specific issue that you can assign me
I can solve it

**Comment by notsoocool** [comment]
I am gonna remove people who are not active from the assigned issues, if you want you can work on that.

**Comment by notsoocool** [comment]
Can i close this issue for now then?

**Comment by Gauravtb2253** [comment]
yes

**Comment by Gauravtb2253** [comment]
pls assign some other issue to me

**Comment by notsoocool** [comment]
@Gauravtb2253 just check any pinned issue and comment on any issue you want to get assigned to

**Comment by notsoocool** [comment]
@Gauravtb2253 i can suggest you something,
currently i don't like 
this switch between snippet Request and snippet delete request in the admin page
<img width="1183" alt="Screenshot 2024-10-19 at 11 21 31 PM" src="https://github.com/user-attachments/assets/3cd9d5af-e8cf-436b-aa96-613796add85f">


Also we don't have a login signup button we are signedout 
<img width="1183" alt="Screenshot 2024-10-19 at 11 21 13 PM" src="https://github.com/user-attachments/assets/36485ce8-cf39-4eaa-aa91-5c392e8479e7">

**Comment by notsoocool** [comment]
You can create a issue out of these two or anything else in you mind.

**Comment by Gauravtb2253** [comment]
so for the second issue do you need two buttons login and signup to be added

**Comment by notsoocool** [comment]
whatever suits best for the design, i don't want to get things cluttered for the navbar, so keep this thing in mind
