### ISSUE TITLE
Improving text visibility

### ISSUE THREAD

**Issue by Gauravtb2253** [notsoocool/codecache#125]
**Is your feature request related to a problem? Please describe.**
Currently the labels of the input fields in add snippets section are not visible clearly

**Describe the solution you'd like**
I would like to change the color and solve it

**Additional context**

![image](https://github.com/user-attachments/assets/2c990a70-58d3-48d2-bd45-a70d3ea18e41)

The labels are not visible clearly, a white color would be better

**Comment by notsoocool** [comment]
@Gauravtb2253 i have already fixed it yesterday, you can see the changes in the develop branch.
