### ISSUE TITLE
Improve the frontend of the home landing page

### ISSUE THREAD

**Issue by Prizag** [notsoocool/codecache#126]
**Is your feature request related to a problem? Please describe.**
The landing page needs to improve its user interactive designs. I will work on it.

**Describe the solution you'd like**
I will improve the frontend of the landing page keeping in mind the theme of the website which will improve user experience.

**Additional context**
![Screenshot 2024-10-19 150319](https://github.com/user-attachments/assets/1dd0ba5a-767f-449d-a1e7-10d415dbe5a9)
###

**Comment by notsoocool** [comment]
Sure @Prizag i will assign you this issue.

**Comment by notsoocool** [comment]
@Prizag we have already update the landing page, so i am going to close this PR now.
