### ISSUE TITLE
real time update of contributors on the readme file

### ISSUE THREAD

**Issue by EfrataAron** [notsoocool/codecache#127]
i noticed that the readme file does not show updated contributors. i want to change this so that it shows all contributors instead of selected few. please assign this issue to me. @notsoocool

**Comment by notsoocool** [comment]
@EfrataAron we already have a workflow for that, if you want you can tweek it lil bit.

**Comment by EfrataAron** [comment]
okay.

**Comment by notsoocool** [comment]
@EfrataAron can you make a PR for develop branch
