### ISSUE TITLE
Adding FAQ Section on Landing Page

### ISSUE THREAD

**Issue by dev129** [notsoocool/codecache#128]
### **Is your feature request related to a problem? Please describe.**
I’ve noticed that users often have recurring questions about our services, offerings, and registration process, and they are unsure where to find answers. This leads to frustration and unnecessary support requests, which could be easily avoided with a clear FAQ section.

### **Describe the solution you'd like**
I would like to implement a dedicated **FAQ section** on the landing page to provide users with immediate answers to common questions. This section should be easily accessible, well-organized, and searchable to improve the user experience. It will help users resolve their queries without needing to contact support and will make the overall website more user-friendly.

### **Describe alternatives you've considered**
I have considered the following alternatives:
1. **Pop-up chatbots** that answer common questions, but this might be intrusive to the user experience, especially on a landing page.
2. **Direct links to a support page**, but this increases the number of clicks needed to find answers.
3. **Including FAQs in the footer**, but this might be overlooked by users who expect FAQ sections in the main content.

### **Additional context**
I envision the FAQ section to be divided into categories such as **General Information**, **Registration Process**, **Event Details**, and **Technical Issues**. It will be designed to be responsive and styled to fit the overall aesthetic of the landing page. Below is an image wireframe representing the general layout.

**Timeline:**
- Wireframe submission: **within 1 hour** of approval.
- Design and pull request: **within 24 hours** after the wireframe is approved.

**Comment by notsoocool** [comment]
@dev129 Go ahead! You can work on this feature. It looks like a great addition to improve the user experience.

**Comment by dev129** [comment]
![wireframe](https://github.com/user-attachments/assets/442a0a62-dea5-4a8b-8e15-017ae57a19cd)
Hi @notsoocool  , this is the perfect wireframe design for your site, if you have another design in mind let me know.

**Comment by notsoocool** [comment]
### A couple of questions before moving forward:

1. Will this feature have a dedicated FAQ page, considering we already have an FAQ section on the landing page?
2. You also mentioned the option of a chatbot. Are you planning to implement that as well, or will it be part of a future update?

**Comment by dev129** [comment]
Okay let me tell you each of them one by one:
1. The FAQ section at your landing page look fine but I think having a dedicated FAQ section is our best bet since it enhances the SEO.
2. The chatbot is something I considered for a while but later it made not much sense because that would degrade the User Experience.

**Comment by notsoocool** [comment]
Thanks for clarifying! I agree that having a dedicated FAQ section can definitely help with SEO, so let's go ahead with that approach. As for the chatbot, I appreciate your consideration, and you're right—a minimalist FAQ section will likely offer a better user experience without overcomplicating things. Let's move forward with your plan!

**Comment by dev129** [comment]
Great I shall start the designing soon.

**Comment by dev129** [comment]
Hi @notsoocool , this is the final design of the all new FAQ Section 

https://github.com/user-attachments/assets/ed36e620-442c-4d8e-baf7-f2ecc41ba45e

When you will approve it I shall raise the PR.

**Comment by dev129** [comment]
Hi @notsoocool , shall I raise the PR with this image :
![image](https://github.com/user-attachments/assets/fdddeca9-1195-4be8-af91-5946408d61b7)
so that it matches your them

**Comment by notsoocool** [comment]
Hi @dev129,

I'm definitely on board with the FAQ page idea, and your design looks promising! However, it doesn’t quite align with the sleek and minimalist UI we're aiming for. Could you please adjust the font to use less bold or semibold weights? Also, please reduce the font size to match our standard usage of either `sm` or `base`. Keeping these points in mind, feel free to raise a PR.

Thanks!

**Comment by dev129** [comment]
Hi @notsoocool,
I’ve just completed the font and design updates to the FAQ section on the landing page. Here’s a quick breakdown of the changes:

1. **Minimalistic Design:** I've reduced the font to a clean, semi-bold style for better readability, while keeping the title of the FAQ section bold as it functions as the hero section. This differentiation ensures a seamless hierarchy and improves focus on key elements.
   
2. **Icons Added for Better UX:** To make the section more intuitive and user-friendly.
https://github.com/user-attachments/assets/8bfcd968-0f51-4fa0-acbf-c390f37a9737

**Comment by notsoocool** [comment]
@dev129 sure just raise the pr and i will review your code and design
