### ISSUE TITLE
Implement Missing Meta Tags for SEO Improvement

### ISSUE THREAD

**Issue by myselfshivams** [notsoocool/codecache#13]
The current website is missing several crucial meta tags that are essential for search engine optimization (SEO). To enhance the site's visibility and ranking on search engines, we need to add the following meta tags:
- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag

Labels:
- GSSoC
- Hacktoberfest

@notsoocool Please assign this issue to me(@myselfshivams).

**Comment by notsoocool** [comment]
Thanks for pointing this out and for your interest in contributing to CodeCache! Implementing these missing meta tags is definitely a crucial step toward improving our SEO and visibility.

I'll assign this issue to you, and I appreciate your enthusiasm to enhance the project! Please ensure that you follow our contributing guidelines, and feel free to reach out if you need any clarification or assistance.
