### ISSUE TITLE
Add quizes and show results

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [notsoocool/codecache#134]
**Is your feature request related to a problem? Please describe.**
Add quizes and show results

**Describe the solution you'd like**
Add quizes and show results

**Describe alternatives you've considered**
Add quizes and show results
**Additional context**

**Comment by notsoocool** [comment]
Hi @KapuluruBhuvaneswariVspdbct,

Thank you for your contribution! However, I’m having trouble understanding the request. Could you please provide more details about how you envision the quiz feature working, and how the results should be displayed? A clearer description or additional context would help in moving forward with this feature.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
i have mentioned two reference images that i have worked during my previous collaboration.
kindly go throught the below images

<img width="953" alt="algostack3" src="https://github.com/user-attachments/assets/aa1d6133-8bb8-409b-9374-1abd51710132">
<img width="865" alt="algostack2" src="https://github.com/user-attachments/assets/fb5c6671-8ef9-44f1-8cd0-402eadb1fcde">

**Comment by notsoocool** [comment]
@KapuluruBhuvaneswariVspdbct I like your idea, you can work on it, but keep it sleek and minimalist use less semibold or bold font, also follow either sm or base as font size
