### ISSUE TITLE
Adding Scroll Progress Bar

### ISSUE THREAD

**Issue by AswaniBolisetti** [notsoocool/codecache#137]
@notsoocool 
I would like to add scroll progress bar
could you please assign it to me

**Comment by RachitSahu26** [comment]
Hi @notsoocool ,

I noticed @AswaniBolisetti has taken on multiple issues but haven't resolved any yet. It becomes difficult for others like me to contribute when someone tries to hold two or three issues at the same time. I would also like to work on this issue, but it’s challenging when others block multiple tasks without completing them.

To the maintainer: Please consider this, as it affects the pace and opportunities for contributors. I resolved this issue in 2 hours and would appreciate it if my efforts were recognized.

Thanks!

**Comment by AswaniBolisetti** [comment]
@RachitSahu26 
I have completed all my issues 
Thank you

**Comment by notsoocool** [comment]
@AswaniBolisetti kindly have a different PR for each issue. I mentioned this earlier, but you still didn't follow my instructions.

**Comment by notsoocool** [comment]
@AswaniBolisetti see, do one thing: make different branches for different issues. It will help you in raising different PRs for different issues. Just do some modifications to successfully achieve the points. Thank you!

**Comment by AswaniBolisetti** [comment]
@notsoocool 
Kindly check it again
I have created seperate branches for all the three issues created by me

**Comment by AswaniBolisetti** [comment]
@notsoocool 
I have created seperate branches as you said
But you closed all my pull requests

**Comment by notsoocool** [comment]
> @notsoocool I have created seperate branches as you said But you closed all my pull requests

Because you have to raise different pull requests with those branches and solve the separate issues in the respective branches.

**Comment by AswaniBolisetti** [comment]
> > @notsoocool I have created seperate branches as you said But you closed all my pull requests
> 
> Because you have to raise different pull requests with those branches and solve the separate issues in the respective branches.

@i raised different pull request that's why in pull requests section there are 3 pull requests created by me

**Comment by AswaniBolisetti** [comment]
@notsoocool 
![Screenshot_2024-10-22-15-46-27-23_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/dbe6544b-32b7-4ba7-ac56-f0d986cfab06)

This doesn't mean I created in single PR

**Comment by notsoocool** [comment]
@AswaniBolisetti first take a deep breath and listen 
<img width="1112" alt="Screenshot 2024-10-22 at 3 51 04 PM" src="https://github.com/user-attachments/assets/01b066b0-8e67-4caf-a19f-cb5919b750cb">

this basically means all changes in one PR even if you raised 3 different PR, the changes and commits are always the same, thats why we have branches to push different commit at a time. You are getting confused with pushing changes one after another and creating 3 different PR, it will always reflect in same changes to all 3 PR, as it was performed to same branch
