### ISSUE TITLE
adding a new contact us page

### ISSUE THREAD

**Issue by Sonuu20** [notsoocool/codecache#141]
I'd like to create a new contact us page for the applications where the individuals can contact with owner of the site.

**Comment by notsoocool** [comment]
I am satisfied by your idea, but you have think about button or place to put the contact us page, as the nav bar is already full.

**Comment by Sonuu20** [comment]
@notsoocool  I've added it in the header but it can be moved to the footer. Here is how it's looks: 
![codecache](https://github.com/user-attachments/assets/99a23bda-e6a1-4d68-8a25-26a89cbba994)

**Comment by notsoocool** [comment]
@Sonuu20 it looks good, i will wait for the PR

**Comment by Sonuu20** [comment]
@notsoocool I've raised the PR under the #162. Please review the pr and merge it..
