### ISSUE TITLE
Design a FAQ page for the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [notsoocool/codecache#156]

**Comment by arpit74170** [comment]
Give me this task please

**Comment by notsoocool** [comment]
@shubhagarwal1 @arpit74170 we already have a FAQ page for the website

**Comment by shubhagarwal1** [comment]
hey @notsoocool can you tell me soemthing other to work on, that would enhance and help the website to upgrade, it would be a greate opportunity for me.

**Comment by notsoocool** [comment]
@shubhagarwal1 can you make the whole website responsive???

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 can you make the whole website responsive???

whole website includes all pages, canyou please share more details

**Comment by notsoocool** [comment]
> > @shubhagarwal1 can you make the whole website responsive???
> 
> whole website includes all pages, canyou please share more details

See, whatever seems not responsive for mobile, you can work on that. It depends on how many pages you want to make responsive, and it will also affect your points.
