### ISSUE TITLE
Implement User Profiles and Contribution Tracking

### ISSUE THREAD

**Issue by notsoocool** [notsoocool/codecache#16]
**Description:** Create detailed user profile pages showcasing the user's contributions, such as submitted snippets, bookmarked snippets, and rated snippets.

- **Functionality:**
  - Display all snippets submitted by the user.
  - Show snippets the user has bookmarked and rated.
  - Include a leaderboard highlighting top contributors.
- **Additional Features:** Allow users to see their activity (e.g., ratings, comments, bookmarks) and show their total contributions and ranking on the leaderboard.
- **Implementation**: Create a user profile page, integrate it with Clerk authentication, and pull data from snippets, bookmarks, and ratings.

**Comment by priyanshuverma-dev** [comment]
May I work on this issue @notsoocool

**Comment by notsoocool** [comment]
Hi @priyanshuverma-dev ,

Thanks for your interest in contributing! 🙌 You are welcome to work on this issue. Feel free to start by creating a branch and share updates or questions as you progress.

Looking forward to seeing your contributions! 🚀

**Comment by priyanshuverma-dev** [comment]
May I Integrate Prisma ORM also as using raw mongodb will increase complexity.

Should create a new issue related to this and assign me if you (please 😁). 

I will solve that first then this issue.
Let me know if it sounds good to you.

Thanks
Priyanshu Verma

**Comment by notsoocool** [comment]
@priyanshuverma-dev comment on the new issue and i will assign it to you

**Comment by priyanshuverma-dev** [comment]
@notsoocool I have pulled PR for prisma migration #29 .
Approved and merge so that I can work on this issue

**Comment by priyanshuverma-dev** [comment]
@notsoocool Which branch should I clone for this Issue. I will use Prisma ??

**Comment by notsoocool** [comment]
@priyanshuverma-dev  Please pull the `develop` branch only and continue working with MongoDB for now. I have kept your Prisma ORM integration under consideration, and if it aligns well with the project, I will merge it later. For the time being, let's proceed with MongoDB.

**Comment by priyanshuverma-dev** [comment]
@notsoocool Sounds good to me but it will conflict because use native mongodb that is not done in `prisma`. Let me work on this and update you.

**Comment by notsoocool** [comment]
> @notsoocool Sounds good to me but it will conflict because use native mongodb that is not done in `prisma`. Let me work on this and update you.

no it wont conflict because i haven't merge you pr in develop branch, it is stored in diff branch

**Comment by priyanshuverma-dev** [comment]
@notsoocool How do we fetch user submitted snippets as we don't store submitted by in snippet model??

**Comment by priyanshuverma-dev** [comment]
And profile requires these fields 
```
const user = {
  name: "Alice Johnson",
  username: "alice_j",
  avatar: "/placeholder.svg?height=100&width=100",
  bio: "Passionate coder and open-source contributor",
  joinDate: "January 2022",
  contributions: 127,
  rank: 5,
}
```
Current have only email. 
Profile Page can be only user centric mean logged user can see his own profile only.
### Profile I have created till know 
![image](https://github.com/user-attachments/assets/36772a42-0b5b-474d-8823-889c92397a36)

### For mobile
![image](https://github.com/user-attachments/assets/7bf28a41-f5fd-42db-ac5f-8913be8973d6)

**Comment by notsoocool** [comment]
Its looking great, so for contributions add points for adding snippets, for bookmarks, editing comments etc etc

**Comment by notsoocool** [comment]
> @notsoocool How do we fetch user submitted snippets as we don't store submitted by in snippet model??

using snippetRequest Model
