### ISSUE TITLE
Feature Request: Enhanced Search & Filtering

### ISSUE THREAD

**Issue by sezallagwal** [notsoocool/codecache#170]
## Description
To improve the usability and efficiency of CodeCache, implement advanced search and filtering capabilities that enable users to find and manage snippets more easily. This feature will allow users to filter snippets by programming language, tags, date created, popularity, and recent usage, as well as provide intelligent search suggestions and versioning for better snippet management.

### Proposed Features
1. **Advanced Search Filters**
   - Allow users to filter snippets by:
     - **Programming Language**: Filter snippets based on the language (e.g., JavaScript, Python).
     - **Tags**: Use custom tags to categorize and search for specific types of snippets.
     - **Date Created**: Filter by creation date to find recently added snippets.
     - **Popularity**: Rank snippets by community engagement (e.g., likes, stars).
     - **Recent Usage**: Sort snippets based on recent usage or modifications.

2. **Search Suggestions & Autocomplete**
   - Provide intelligent search suggestions to improve the search experience.
   - Implement autocomplete for frequently searched terms and tags.
   - Offer recommendations based on recently accessed snippets and similar tags or keywords.

## Expected Outcome
With these enhanced search and filtering features, users will be able to navigate CodeCache more effectively, find the exact snippets they need, and manage their code history with ease.

---

Please assign this issue under the `gssoc-ext` and `hacktoberfest` labels.

**Comment by notsoocool** [comment]
Sure, @sezallagwal! Currently, we're only searching through titles and filtering by tags. If you can add an option to search through tags and categories, that would be great!

**Comment by sezallagwal** [comment]
yup I can do that assign me @notsoocool
