### ISSUE TITLE
Add subscribe to our platform

### ISSUE THREAD

**Issue by haseebzaki-07** [notsoocool/codecache#171]
**Is your feature request related to a problem? Please describe.**
I want to add subscribing feature to the application so that users filling in their email ids in the footer of the website receive a confirmation mail to their valid mail ids.
Users will receive the confirmation mail and a success toast will be shown on the website.

**Describe the solution you'd like**
I will create backend api for the mail sending purpose and also a frontend component where users can fill in their mail ids for subscription.

**Comment by notsoocool** [comment]
@haseebzaki-07 You can enhance this in the FAQ page. I believe there’s a button there, but it's currently not working or fully functional.

**Comment by haseebzaki-07** [comment]
Sure and please assign me the issue @notsoocool
