### ISSUE TITLE
Ui: the FAQ section has some misalignments

### ISSUE THREAD

**Issue by AE-Hertz** [notsoocool/codecache#178]
**Describe the bug**
The FAQ section has misalignments the alignments it should be consistent and match to the main theme of the site.

**To Reproduce**
1. Go to the site in mobile devices 
2. Scroll down to faw section 

**Expected behavior**
Perfectly aligned the FAQ section and make it consistent.

**Screenshots**
![1000016715](https://github.com/user-attachments/assets/43884e26-ace0-4e5b-8a33-e87a224d91c0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign me this under hacktoberfest and gssoc-ext

**Comment by AE-Hertz** [comment]
@notsoocool can you please assign me

**Comment by KaroK365** [comment]
I would like to contribute to it

**Comment by notsoocool** [comment]
@AE-Hertz sure you can fix it, just don't change the UI

**Comment by AE-Hertz** [comment]
for sure.
