### ISSUE TITLE
feat: add dynamic copyright section 

### ISSUE THREAD

**Issue by AE-Hertz** [notsoocool/codecache#179]
**Is your feature request related to a problem? Please describe.**
The copyright section plays crucial role and important for the site. One of the main reason why people don't use it as it needs to update each year.

**Describe the solution you'd like**
But I will make a dynamic copyright section that will update automatically till the world exists.

**Additional context**

Assign me this under hacktoberfest and gssoc-ext

**Comment by AE-Hertz** [comment]
@notsoocool can you please assign me this

**Comment by KaroK365** [comment]
I would like to contribute to it

**Comment by notsoocool** [comment]
@AE-Hertz if you can add copyright without changes the ui of the footer than i will gladly accept your PR

**Comment by AE-Hertz** [comment]
@notsoocool sure, i am working on it.
