### ISSUE TITLE
Add Comments and Discussion Feature for Code Snippets

### ISSUE THREAD

**Issue by notsoocool** [notsoocool/codecache#18]
**Description:** Enable users to leave comments, ask questions, or provide feedback on code snippets, fostering a community around each snippet.

- **Functionality:** Allow users to post comments under snippets. Enable replies to comments and allow the snippet author to moderate or delete inappropriate comments.
- **Additional Features:** Provide notifications to snippet owners when comments are posted.
- **Implementation:** Create a comment model and API to store and fetch comments. Use Clerk for user authentication and integrate comment functionality on the snippet detail page.

**Comment by Vivek7038** [comment]
@notsoocool  Can you assign me these one 
I want to give a try to create and get comments.i worked with clerk in the past as well.

**Comment by notsoocool** [comment]
Hi @Vivek7038,

Thank you for your interest in working on this feature! Since you have experience with Clerk, you can definitely take this one on. I'll go ahead and assign it to you. Feel free to reach out if you have any questions during implementation or need any clarification.

Looking forward to seeing your contributions!

**Comment by Vivek7038** [comment]
@notsoocool  i am taking pull from main branch and then creating a new branch from main. 
Is these works or i have to create new branch from develop

**Comment by notsoocool** [comment]
@Vivek7038 the best practice would be to pull from the **develop** branch instead of the **main** branch. We’ve made some changes in the develop branch that aren’t available in the main branch, and starting from develop will help prevent any potential conflicts down the line.

**Comment by Vivek7038** [comment]
@notsoocool how the newly added snippets approval work , currently its getting added to snippetrequests collection, how to approve it
![image](https://github.com/user-attachments/assets/67b7e6ef-f91f-4ea9-b05f-8bc07be3be71)

**Comment by Vivek7038** [comment]
Basically i want to experiement adding comments on the dummy snippets which i created.

**Comment by notsoocool** [comment]
okay, now check .env.sample file in the develop branch, there i added the field for 
ADMIN_USER_IDS= <yourclerkuserid>
here just replace the value with you clerk user id.
so what you have to do is open the clerk app and check for your email and copy the user id and paste it here

**Comment by Vivek7038** [comment]
Quick updates :

Post and get api for comments is sorted and working perfect . 

Remaining thing is UI for showing comments and adding comments 
![image](https://github.com/user-attachments/assets/03575851-cafa-45af-a00c-cd00d4bc40bb)

**Comment by Vivek7038** [comment]
![image](https://github.com/user-attachments/assets/778d7064-6675-4aa4-b443-d62d3bf89137)

**Comment by Vivek7038** [comment]
raised a pr #37

**Comment by notsoocool** [comment]
> raised a pr #37
@Vivek7038 
Thank you for raising the PR! I'll make sure to review it as soon as I get some time. Appreciate your contribution!
