### ISSUE TITLE
[Bug ] : Contributor page should be fixed.

### ISSUE THREAD

**Issue by Akshithsaai** [notsoocool/codecache#193]
**Describe the bug**
Contributor page  doesnot fetch entire data using your api call. If no of contributors are more than 30 you will get only 1st page data. The Github API uses pagination and limited to per_page 100 ids and default is 30. 

**Expected behavior**
If the contributors increase more than 30 then this change is mandatory. 

**Additional context**
@notsoocool I have developed a solution for this.

**Comment by notsoocool** [comment]
Okay @Akshithsaai i will review it once I get some time.

**Comment by Akshithsaai** [comment]
@notsoocool Ok, Please suggest any changes ,if any . 
I have linked the PR to this issue.
