### ISSUE TITLE
Want to add security

### ISSUE THREAD

**Issue by Dipanita45** [notsoocool/codecache#198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by notsoocool** [comment]
@Dipanita45 kindly have a perfect description to your issue, i am not getting what you are trying to say

**Comment by Dipanita45** [comment]
I will add security file in.md extension

**Comment by Dipanita45** [comment]
Please assign me this issue

**Comment by notsoocool** [comment]
Okay @Dipanita45 but can you describe what does this security file consist of ??

**Comment by Dipanita45** [comment]
It consists of how to report , vulnerability,...etc

**Comment by notsoocool** [comment]
okay go ahead.
