### ISSUE TITLE
Redesigning landing page

### ISSUE THREAD

**Issue by Anushkam09** [notsoocool/codecache#25]
**Is your feature request related to a problem? Please describe.**
I feel that there is too text on the landing page. With animated websites used nowadays, that much text in one go is too much for a user. Especially new ones.

**Describe the solution you'd like**
I would like to redesign the landing page:
1. Add animations, make different sections
2. Reduce texts, improve font size and combination

Current landing page:
![image](https://github.com/user-attachments/assets/23e21f02-1846-40fc-a682-b7a91f99dc13)

**Comment by notsoocool** [comment]
Hi @Anushkam09,

Thank you for your suggestion! I agree that improving the landing page's design and reducing text could enhance the user experience. I'd love to see how you can make the page more engaging with animations and a better layout. Looking forward to your redesign!

**Comment by notsoocool** [comment]
@Anushkam09 
Hello! It's been more than 3 days since this issue was assigned. If you’re still working on it, please provide an update. Otherwise, I will need to remove you from the assignment to free it up for others to take over. Thank you!

**Comment by EfrataAron** [comment]
i can work on the landing page. assign it to me

**Comment by notsoocool** [comment]
@EfrataAron any updates?

**Comment by EfrataAron** [comment]
@notsoocool check your discord, im trying to reach you

**Comment by EfrataAron** [comment]
i have gone through the project structure and im working on the landing page. @notsoocool

**Comment by notsoocool** [comment]
Sure @EfrataAro, and sorry, I was busy which is why I didn’t see your message on Discord.
