### ISSUE TITLE
Snippets Approve not working 

### ISSUE THREAD

**Issue by Vivek7038** [notsoocool/codecache#26]
**Describe the bug**

when we navigate to admin page on /root route we can approve or reject the snippets .Reject works perfect but when we try to accept it throws the error 
**To Reproduce**
1. Go to   admin page 
2. Click on  Approve of any pending snippet 
3. It gives you a toast message "Error accepting snippet request"

**Expected behavior**
we should be able to approve seemlessly 
**Screenshots**
![image](https://github.com/user-attachments/assets/c97b6d6e-7590-4482-9bd9-004d12018fad)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vivek7038** [comment]
Hey @notsoocool Can you add it under gssoc-ext and also the level and assign me, i have the solution in my local repo

**Comment by Vivek7038** [comment]
I solved the issue just add the labels so that i can raise pr

**Comment by notsoocool** [comment]
it because you have not filled all the property, thats why its throwing an error

**Comment by notsoocool** [comment]
Sure you can go ahead, i dont know how it was not working, it was working before

**Comment by notsoocool** [comment]
> Sure you can go ahead, i dont know how it is not working, it was working before

i checked got the error, you can go ahead, if you get stuck do tell me

**Comment by Vivek7038** [comment]
raise a pr #28 to resolve the issue
