### ISSUE TITLE
Integrate Prisma ORM to Replace MongoDB Usage (TESTING)

### ISSUE THREAD

**Issue by notsoocool** [notsoocool/codecache#27]
Using raw MongoDB increases complexity in the project. We will integrate Prisma ORM to simplify database interactions and improve maintainability. The following steps will be taken:

- Replace current MongoDB models and queries with Prisma models and queries.
- Update all API routes to use Prisma.
- Ensure that the existing functionalities (e.g., snippets, ratings, user permissions) work seamlessly after the migration.
Assignee: @priyanshuverma-dev
Branch: Use the newly created branch for this issue and raise a PR once completed.

**Comment by priyanshuverma-dev** [comment]
Awesome choice.I can work on this issue
