### ISSUE TITLE
Enhancement: Add 10 New Code Snippets

### ISSUE THREAD

**Issue by shubhagarwal1** [notsoocool/codecache#30]
1. JavaScript: Arrow Functions
2. JavaScript: Reduce Method
3. JavaScript: Set Timeout Example
4. Python: Dictionary Methods
5. Python: Try Except Block
6. Java: Switch Statement
7. Java: LinkedList Example
8. HTML: Button Element
9. CSS: Box Shadow
10. CSS: Positioning Example (absolute, relative)

**Comment by notsoocool** [comment]
@shubhagarwal1 thanks for the suggestion! However, snippets can only be added through the website, so there’s no need for a separate issue for adding them via code. You can go through the existing codebase to find any errors or suggest enhancements. Alternatively, you can pick any of the open issues to work on.
