### ISSUE TITLE
Accepting snippet request as admin doesn't work

### ISSUE THREAD

**Issue by Agnish1611** [notsoocool/codecache#32]
**Bug Description**
When you login as an admin, and try to accept a pending snippet request, it will fail to accept the request.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a snippet for testing
2. Login as an admin
3. Go to the Admin page
4. Click on Accept for accepting the test snippet
5. See error 

**Expected behaviour**
The admin is able to accept requests without any error.

**Screenshots**

![Screenshot 2024-10-05 021709](https://github.com/user-attachments/assets/9613be84-6967-4028-a4b1-8599074585cd)

**Desktop:**
 - OS: Windows 11
 - Browser: chrome
 - Version: 129.0.6668.90

**Probable error:**
In `app/api/request/accept/route.ts` the code for adding the `newSnippet` is missing parameters like category, difficulty and usage which are required fields.

Please assign this to me and add necessary tags. I would like to solve this bug.

**Comment by notsoocool** [comment]
@Agnish1611 its already fixed, you can check it in the 'develop' branch.

**Comment by Agnish1611** [comment]
Oh thanks for pointing it out. I must have overlooked it.
