### ISSUE TITLE
Theme toggle issue

### ISSUE THREAD

**Issue by Sourabh782** [notsoocool/codecache#36]
**Is your feature request related to a problem? Please describe.**
Currently when we are clicking on theme toggle, it opens a pop up to select theme.

![Screenshot 2024-10-05 185540](https://github.com/user-attachments/assets/71ab1b51-c133-470c-9e31-698003752709)

But i think if someone is clicking on theme toggle button, its obvious he want to switch themes, so why add an extra step.

**Describe the solution you'd like**
I want to remove popup and directly change theme, cause popup adds an extra step for user.

**Describe alternatives you've considered**
For system default setting, we will keep default theme mode on basis of system preference

**Additional context**
I want to work on this issue

**Comment by notsoocool** [comment]
@Sourabh782 Thank you for the suggestion! However, I believe keeping the popup allows users to deliberately choose the theme they want, without triggering an accidental switch. This extra step ensures clarity and avoids sudden changes that might disrupt the user experience. But feel free to share more insights if you think it could be improved further!
