### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [notsoocool/codecache#38]
Add the contributors automatically to readme which basically enhaces the repo visibility
Hey @notsoocool please assign this task to me with level tag

**Comment by shubhagarwal1** [comment]
Thankyou for assigning, Starting working on it

**Comment by notsoocool** [comment]
If you don't mind @shubhagarwal1 can also build a workflow to automatically label the issues and repos with `gssoc-ext` and `hacktoberfest-accepted` label. I will label your pr with level2 if done so.

**Comment by shubhagarwal1** [comment]
> If you don't mind @shubhagarwal1 can also build a workflow to automatically label the issues and repos with `gssoc-ext` and `hacktoberfest-accepted` label. I will label your pr with level2 if done so.

sounds good

**Comment by shubhagarwal1** [comment]
please assign the task under labels please

**Comment by notsoocool** [comment]
@shubhagarwal1 are both the files running successfully? Have you tested it locally on your repository?

**Comment by notsoocool** [comment]
And also please don't open 2 diff PR just make it one.

**Comment by shubhagarwal1** [comment]
> And also please don't open 2 diff PR just make it one.

i have opened two PR so that each functionality can get tested diffently 
that is the only reaosn i have opened two PR though in seperate branch so if we have any changes we can manage them separately

**Comment by notsoocool** [comment]
@shubhagarwal1 the file is working perfectly but the code is wrong
kindly check the code
