### ISSUE TITLE
Mobile Responsive Website

### ISSUE THREAD

**Issue by rajatsinghal02** [notsoocool/codecache#39]
I want to create a Mobile Responsive Snippet Page..
![Screenshot_20241006_101512](https://github.com/user-attachments/assets/e4ad9107-cade-44d1-bf0a-2485c6bcaba3)

@notsoocool Please assign this issue to me. I want to resolve this issue.
@notsoocool please add the required lables attached with level 2 support.

**Comment by notsoocool** [comment]
**@rajatsinghal02** That sounds like a great idea! Feel free to go ahead and start working on making the Snippet Page mobile responsive. Let me know if you need any assistance or clarification while working on it. Also pull develop branch for contributing to the project.

**Comment by ZayedShahcode** [comment]
Hey @notsoocool, I observed add snippet page is also not responsive on mobile.
Can I work on that under this issue or raise separate issue.

![WhatsApp Image 2024-10-06 at 5 28 00 PM](https://github.com/user-attachments/assets/31f406f2-d9ae-48ff-8a58-aa4fb7c4d103)

**Comment by notsoocool** [comment]
@ZayedShahcode sure no need for another issue you can work under the same issue

**Comment by inkerton** [comment]
HI @notsoocool can I work on this too.

**Comment by inkerton** [comment]
@notsoocool  Please look at the PR and merge it I resolved the issue.

**Comment by notsoocool** [comment]
@rajatsinghal02 
Hello! It's been 2 days since this issue was assigned. If you’re still working on it, please provide an update. Otherwise, I will need to remove you from the assignment to free it up for others to take over. Thank you!

**Comment by rudrapratap63** [comment]
Hello! @notsoocool  Could you please assign issue #39 to me? I’m ready to start working on it. Thank you😊 !

**Comment by rudrapratap63** [comment]
Thank you @notsoocool sir, I will start working on it.

**Comment by Codersweta7** [comment]
@notsoocool please assist this to me if the work is not done yet , becoz maximum it takes 1 day to make a website responsive for mobile or some screen .

**Comment by notsoocool** [comment]
@Codersweta7 i am not able to see your comment

**Comment by notsoocool** [comment]
Hi @rudrapratap63 ,

It’s been a week without any updates. I will be closing this issue by the end of the day. If you have any progress to share, please do so before then.

Thank you!

**Comment by Codersweta7** [comment]
@notsoocool 
I wanted to work upon this , but your project is not using css , I think ..so I can't apply .

**Comment by notsoocool** [comment]
@Codersweta7 we have use tailwindcss it is pretty much same you can check the documentation here https://tailwindcss.com/docs/installation

**Comment by Codersweta7** [comment]
@notsoocool 
Okay assign me I will study and work upon it but I need sometime ....becoz there is some issue in my system , once sorted I will work upon it .

**Comment by notsoocool** [comment]
Okay just work on the issue, as i will be creating a new issue tomorrow with the same cause, so just comment there and i will assign you.

**Comment by Codersweta7** [comment]
> Okay just work on the issue, as i will be creating a new issue tomorrow with the same cause, so just comment there and i will assign you.

Kindly tag me if possible ...🙂
