### ISSUE TITLE
feat: Design changes in Dropdown Avatar card

### ISSUE THREAD

**Issue by tarunkumar2005** [notsoocool/codecache#40]
**Describe the bug**
So if we have a proper name of the user then we can make use of that and in profile section in place of direct email we can show the name okay and people don't just randomly put anything and forget about it and to enhance security we can add the confirm password field so that i want to do.

**To Reproduce**
1. Go to signup page
2. there you can see the fields.

**Screenshots**
![image](https://github.com/user-attachments/assets/9d69c089-ffe4-4a2d-bc37-523ccc09bc84)

in place of email we can put the name of the user here which is better option.

**Comment by tarunkumar2005** [comment]
@notsoocool Assign this to me under gssoc 2024 ext and hacktoberfest.

**Comment by notsoocool** [comment]
@tarunkumar2005 If you have experience with Clerk, feel free to go ahead and implement the changes! Let me know if you need any assistance along the way.

**Comment by tarunkumar2005** [comment]
It can be level 2 as i am not just adding the fields to the form but also implemnting them to the profile page with clerk ?? @notsoocool

**Comment by notsoocool** [comment]
I appreciate your concern @tarunkumar2005, but that totally depends on your PR. If it’s worthy of a level 2 or 3, I’ll assign it to you without any bias. However, this issue is labeled as level 1 because it doesn’t address a major or moderate problem.

**Comment by tarunkumar2005** [comment]
one more thing i can't change the things they will reflect on my clerk account only so i can just guide you what to do how will i create a pull req then

**Comment by tarunkumar2005** [comment]
I have done what i was telling in the issue but it is for my account not yours so what to do in this case @notsoocool

**Comment by tarunkumar2005** [comment]
@notsoocool Where you want that card i can't understand it properly there is already a signout button or if you want to replace this profile section from clerk to custom one that you are saying can you elobrate on that.

**Comment by notsoocool** [comment]
Yes i was talking about custom one, if you are ready to do so

**Comment by tarunkumar2005** [comment]
Okay i will create that in place of this default one by clerk. Thank you for suggestion i will work on it.
