### ISSUE TITLE
The buttons in documentation page are not functional

### ISSUE THREAD

**Issue by subin-shk** [notsoocool/codecache#42]
The buttons to github, linkedin and x (formely twitter) are not functional. And i think its better to use icon of X instead of old twitter account. I am a beginner.
 Please assign it to me.

1. Go to Documentation from navbar
2. Click on the github, linkedin, twitter icon
3. See error

**Expected behavior**
Upon clicking the icons the page should redirect to respective links.

**Screenshots**
![image](https://github.com/user-attachments/assets/a6efcacb-0869-4721-8f74-dce38c7efc21)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126

**Smartphone (please complete the following information):**
 - Device: Redmi Note 11
 - OS: MIUI 14
 - Browser: Google Chrome
 - Version 129

**Comment by notsoocool** [comment]
Hey @subin-shk , thanks for offering to take this on! Just a heads-up that the current documentation page is temporary, so I don't need any changes to it right now. However, if you're interested, you can create a new documentation page after thoroughly going through the website and understanding how everything works. Let me know if you're up for that challenge! 😊

**Comment by subin-shk** [comment]
@notsoocool what sort of things would you prefer to add on your new documentation page?

**Comment by notsoocool** [comment]
Actually the Main landing page is getting revamped, so what you can do is, you can bring out things from landing page here and also add some few more things.
