### ISSUE TITLE
Add snippet page is also not responsive on mobile.

### ISSUE THREAD

**Issue by notsoocool** [notsoocool/codecache#48]
Hey @notsoocool, I observed add snippet page is also not responsive on mobile.
Can I work on that under this issue or raise separate issue.

![WhatsApp Image 2024-10-06 at 5 28 00 PM](https://github.com/user-attachments/assets/31f406f2-d9ae-48ff-8a58-aa4fb7c4d103)

_Originally posted by @ZayedShahcode in https://github.com/notsoocool/codecache/issues/39#issuecomment-2395452518_

**Comment by notsoocool** [comment]
@ZayedShahcode need you comment here to assign you the issue and further closeit

**Comment by ZayedShahcode** [comment]
Ok sure.
