### ISSUE TITLE
Client-side exception error on accessing the /bookmarks page

### ISSUE THREAD

**Issue by KumarAmrendram** [notsoocool/codecache#54]
**Description**
A client-side exception occurs when trying to access the /bookmarks page, resulting in the page not loading and displaying the following error message:
"Application error: a client-side exception has occurred (see the browser console for more information)."

**Steps to reproduce the behavior:**
  1. Go to https://codecache.tech/bookmarks
  2. Observe the page load error.

**Expected behavior:**
The page should load successfully, displaying the user's bookmarks without throwing any client-side exceptions.

**Screenshots**
<img width="1677" alt="Screenshot 2024-10-07 at 9 27 44 PM" src="https://github.com/user-attachments/assets/0c7be212-bbaa-4330-9bdd-39be84001b98">

**Desktop:**
OS: macOS Sonoma
Browser: Chrome

**Additional context**
This issue could be related to JavaScript or React rendering logic on the /bookmarks page. The error suggests a problem in the client-side code.
I would like to solve this issue as part of Hacktoberfest and GSSoC contributions.

**Comment by notsoocool** [comment]
Hi @KumarAmrendram ,
I’ve understood the cause of this error, but if you’d like to solve it yourself, I can assign the issue to you. Let me know how you'd like to proceed!

**Comment by inkerton** [comment]
Hi @notsoocool  I was the one who made the bookmarks page so I would like to solve the error I know what might have caused this I will put in some error handling methods on the bookmarks page.

**Comment by notsoocool** [comment]
@KumarAmrendram, please avoid closing issues on your own. Consider this a warning for this time.

**Comment by KumarAmrendram** [comment]
I'm really sorry. I wasn't aware about the process. I will take care of it next time.
