### ISSUE TITLE
ADD: Implement Auto-Labeling Workflow for GitHub

### ISSUE THREAD

**Issue by samyak-aditya** [notsoocool/codecache#56]
**Is your feature request related to a problem? Please describe.**

This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests

**Additional context**
Hey @notsoocool Please assign me this Task

**Comment by samyak-aditya** [comment]
Hey @notsoocool I have raised the PR

**Comment by notsoocool** [comment]
@samyak-aditya I will be reopening this issue if the PR doesn’t work or solve the mentioned problem. Additionally, I might revert the changes in the PR or remove the labels associated with it.
