### ISSUE TITLE
Improve Overall Responsiveness of the Website

### ISSUE THREAD

**Issue by rudrapratap63** [notsoocool/codecache#58]
**Is your feature request related to a problem? Please describe.**
The website currently lacks responsiveness, leading to a poor user experience on various screen sizes.

**Describe the solution you'd like**
I would like the website to have a fully responsive design that adapts to different screen sizes seamlessly.

**Additional context**
- In the navigation bar, the hamburger menu, search bar, and account profile section collapse improperly on smaller screens.
- The "Snippets" and "Add Snippets" pages are not responsive and their content does not scale correctly on mobile devices.

Video of the current design and suggestions for improvement can be provided upon request.
https://github.com/user-attachments/assets/12053e87-c228-43a6-bee4-777517a33779

**Comment by notsoocool** [comment]
@rudrapratap63, I understand your concern, but there is already an existing issue with the same objective #39. Kind comment there and I'll assign that to you. Additionally, I'll update the issue title so you can work on the responsiveness of all the pages. Please make sure to fetch the latest changes from the develop branch, make your updates, and raise the PR for the develop branch only. Thank you!

**Comment by rudrapratap63** [comment]
Thank you for the clarification! I’ll comment on issue #39 as suggested. I’ll also ensure I work on the responsiveness of all pages. I’ll make sure to fetch the latest changes from the develop branch and submit the PR to the same branch.

Appreciate your guidance!
