### ISSUE TITLE
Conditional Rendering NavBar & Route protection

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#62]
**Describe the bug**
Bookmarks page, My snippets should only be visible after the user has logged in.

**To Reproduce**
1. Go to 'website'
2. See Navbar

**Expected behavior**
These labels should be visible after user has logged in to avoid confusion and errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/24bc27f2-77ca-4f67-b119-7e7777befb01)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by inkerton** [comment]
@notsoocool If the issue is acceptable then assign it to me I would like to work on it.

**Comment by notsoocool** [comment]
@inkerton yes go ahead, i am assigning this issue to you, but only do it for Bookmark page, as we are gonna make few changes to my snippet page
