### ISSUE TITLE
Bug: Contributors List not displaying

### ISSUE THREAD

**Issue by yashksaini-coder** [notsoocool/codecache#64]
**Describe the bug**
The contributors list header marker are not correctly formatted, and the list is not displaying. 
Also the GitHub Token used in the repo should have permissions of user, repo, workflows, access etc.

**Expected behavior**
With the workflow action execution a table of contributors will be generated & added in the markers section

**Screenshots**
NA 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by yashksaini-coder** [comment]
@notsoocool Review this issue and add labels to it `gssoc-ext`, `hacktoberfest` and `level` etc

**Comment by notsoocool** [comment]
@yashksaini-coder kindly solve this issue under #38

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder kindly solve this issue under #38

its not my issue

**Comment by notsoocool** [comment]
Sorry under #49

**Comment by yashksaini-coder** [comment]
> Sorry under #49

okh i will sove it under #49 but tell me why can't I raise a new issue to point the Bug-fix

**Comment by notsoocool** [comment]
> > Sorry under #49
> 
> okh i will sove it under #49 but tell me why can't I raise a new issue to point the Bug-fix

It's because you already created an issue (#49) and raised a PR that didn’t fully resolve it. There’s no need to create a new issue for the same problem. 

I'm allowing the PR to go through since it also included updates to the README. Otherwise, I would have reverted the PR directly.
