### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by AasthaSingh28** [notsoocool/codecache#67]
Organizing and properly formatting code snippets will make it easier for developers to read and understand the stored code. This will improve collaboration, reduce time spent on debugging, and make the codebase more maintainable. Consider using consistent indentation, comments, and tools like linters to ensure code readability.

@notsoocool -kindly assign me this issue, i want to work on this.

**Comment by notsoocool** [comment]
@AasthaSingh28 Sure, go ahead! But remember to fetch from the `develop` branch and also raise a PR for the `develop` branch only.
