### ISSUE TITLE
Add option to select language while adding the snippet

### ISSUE THREAD

**Issue by Suhas-Koheda** [notsoocool/codecache#7]
**Describe the bug**
It looks like the language section in the add snippet does not check if the language is valid or not 
it would be good if there is a drop down to choose the languages from the below such

**To Reproduce**
1. Go to 'Add Snippet'
2. Click on 'Language'
3. Any language can be written

**Expected behavior**
A drop down can be added to enable user to chose form one of the programming langauge

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Suhas-Koheda** [comment]
hey @notsoocool 
if you feel the issue is valid can you please assign this to me 
i would like to solve this under gssoc24 extnd and hacktoberfest

**Comment by notsoocool** [comment]
Sure! Thank you for pointing this out. Before proceeding, kindly make sure to review the contributing guidelines and the coding standards for the project to maintain consistency. We encourage the use of a dropdown to restrict language input and ensure that users can only select from supported languages.

Feel free to suggest a list of commonly used programming languages if you have one in mind, or I can provide one for you. You can create a branch for this issue and submit a pull request once you're ready.
