### ISSUE TITLE
Can not Add Snippet

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#73]
**Describe the bug**
Cannot add snippet since their is some mismatch between the frontend and backend 

**To Reproduce**
1. Go to 'Add Snippet'
2. Fill the details
3. Click on 'Add Snippet'

**Expected behavior**
Expected to store the snippet.

**Screenshots**
![image](https://github.com/user-attachments/assets/4820485d-dbec-44d4-a5bc-39c13ba609f7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by inkerton** [comment]
@notsoocool I will solve it then work on the styling of submitted snippets page

**Comment by notsoocool** [comment]
No its working perfe
