### ISSUE TITLE
Delete Snippet

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#74]
**Is your feature request related to a problem? Please describe.**
Add a delete button to delete any submitted snippet

**Describe the solution you'd like**
Making a DELETE request

**Describe alternatives you've considered**

**Additional context**

**Comment by notsoocool** [comment]
Are you gonna work on the mysnippet section on myprofile page ui or this issue?

**Comment by inkerton** [comment]
MY Profile Page UI is done and I was thinking of adding it there only the user can delete only the snippets submitted by them I would give then a delete icon on the top right corner of the snippet from where they may send a delete request and I will seperate the rendering of bookmarked snippets and Submitted snippets .

I already made a PR for the UI changes #71 
I pushed the new changes in there only reverted the changes I made in the route and added styling If you want anything more do let me know.
@notsoocool

**Comment by notsoocool** [comment]
Okay then i am assigning you this issue

**Comment by inkerton** [comment]
@notsoocool DO checkout the PR .

I had worked on it till late to finish it on the same day and It has been 2 days since I made the PR.
