### ISSUE TITLE
Edit Snippet Feature

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#78]
**Is your feature request related to a problem? Please describe.**
Currently their is no way of editing the snippets. I want to give an edit option as weel to the user I was thinking of giving an edit option beside the delete icon in the My Profile page.

**Describe the solution you'd like**
Solution would be to let the user Edit the snippet and save the edited snippet.

**Describe alternatives you've considered**

**Additional context**

**Comment by inkerton** [comment]
@notsoocool Assign the issue to me and let me know what type of edit page you want. I submitted a PR for delete snippet. Also  I keep getting this error I was not sure if I should make a separate issue for it. If this would count I will first work on this bug then work on edit.

![image](https://github.com/user-attachments/assets/7ebdeb06-06a5-44cc-82f0-ecc6344f4927)

**Comment by inkerton** [comment]
here since title is required in the model no snippet has null as a title but I don't know why this error occured . @notsoocool

**Comment by notsoocool** [comment]
> @notsoocool Assign the issue to me and let me know what type of edit page you want. I submitted a PR for delete snippet. Also I keep getting this error I was not sure if I should make a separate issue for it. If this would count I will first work on this bug then work on edit.
> 
> ![image](https://private-user-images.githubusercontent.com/127668005/374622833-7ebdeb06-06a5-44cc-82f0-ecc6344f4927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDE1OTAsIm5iZiI6MTcyODQwMTI5MCwicGF0aCI6Ii8xMjc2NjgwMDUvMzc0NjIyODMzLTdlYmRlYjA2LTA2YTUtNDRjYy04MmYwLWVjYzYzNDRmNDkyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNTI4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzk5OTliYjNkNTE3YWIyYzY3NTJjNmI1ZmY5NzZjNjBlYTI4MmY4MTBjNDdhY2IxYTgyNzU0Yzk4YTYxNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0eGSXW71lOkZFfU3IFGfYJxaUbXkSR0qQXEvyVsqwFI)

sometimes it shows this error, because ig the snippet are not loaded which reflects in this error

**Comment by notsoocool** [comment]
> **Is your feature request related to a problem? Please describe.** Currently their is no way of editing the snippets. I want to give an edit option as weel to the user I was thinking of giving an edit option beside the delete icon in the My Profile page.
> 
> **Describe the solution you'd like** Solution would be to let the user Edit the snippet and save the edited snippet.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

i will assign this issue to you, but first complete the delete feature as mentioned
