### ISSUE TITLE
Chrome console error when clicking on snippet option on sidebar 

### ISSUE THREAD

**Issue by mehul-m-prajapati** [notsoocool/codecache#79]
**Describe the bug**
Chrome console error : `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

**To Reproduce**
1. Go to Chrome inspect
2. Click on console
3. Scroll down to console

**Expected behavior**
no error should be present

**Screenshots**
![d1](https://github.com/user-attachments/assets/e339e7ab-0199-4f44-a969-cb9a668e9e16)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version -129.0.6668.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by notsoocool** [comment]
Hi @mehul-m-prajapati,

You cannot close issues without prior notice. This serves as a warning for this time. Please make sure to communicate before closing any issues in the future.

Thank you!

**Comment by mehul-m-prajapati** [comment]
@notsoocool : Sorry about that, but, I am not getting this error in new changes now. You can close this one.

**Comment by mehul-m-prajapati** [comment]
@notsoocool : sorry about that. I see that it comes from node_modules which are installed locally on my system. You can close this one.
