### ISSUE TITLE
Bookmarks Page 

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#8]
**Is your feature request related to a problem? Please describe.**
I want to add a feature for the users to see the bookmarked code snippets as currently their is no way for them to see their bookmarked snippets. 

**Describe the solution you'd like**
I would like to add a page where they may see all their bookmarked snippets.

**Comment by inkerton** [comment]
hey @notsoocool 
i would like to solve this under gssoc24 extnd and hacktoberfest. Kindly assign it to me.

**Comment by notsoocool** [comment]
Hi @inkerton,
Thank you for the feature request! Yes, adding a page to display bookmarked snippets would be a great enhancement to the user experience. Currently, users can bookmark snippets, but having a dedicated page where they can easily view and manage all their bookmarked snippets would make it more convenient.

**Comment by notsoocool** [comment]
_ref:_ https://github.com/notsoocool/codecache/issues/20#issuecomment-2389259257
_for help_

**Comment by notsoocool** [comment]
Connect me on Discord if you are getting stuck with something
Discord id: notsoisocool

**Comment by notsoocool** [comment]
@inkerton 
Hello! It's been 3 days since this issue was assigned. If you’re still working on it, please provide an update. Otherwise, I will need to remove you from the assignment to free it up for others to take over. Thank you!

**Comment by inkerton** [comment]
I am working on it working with dummy data and admin rights was an issue I was also wondering where do I put the Bookmarks page in the navigation bar above or somewhere else.
