### ISSUE TITLE
[Enhancement]: Improve FAQ Section with Accordion Functionality

### ISSUE THREAD

**Issue by Someshog** [notsoocool/codecache#80]
**Description:**

To enhance user experience in the FAQ section, we propose implementing an accordion feature that allows only _**one question to be opened at a time.**_ This will help declutter the interface, making it easier for users to focus on one answer without being overwhelmed by multiple open questions.

**Objectives:**
- Ensure that when a user opens a question, any previously opened question automatically closes.
- Maintain a smooth and responsive user interface while adding the feature.
- Ensure compatibility across all devices and browsers.

**Screenshots:**

Here, three FAQs are active at a time, which creates confusion sometimes. It would be easier for users to focus on one question and its corresponding answer at once, allowing users to expand a single question while automatically collapsing any others.

![image](https://github.com/user-attachments/assets/a3273735-237f-4e85-aa83-f6bbeedf32c9)

**Additional context**
N/A

**Comment by Soumya880** [comment]
@notsoocool I want to work on it, Can you assign it to me?

**Comment by notsoocool** [comment]
I like your idea, but I think I’ll stick with the original accordion functionality for now. It seems to align better with what I’m looking for.
