### ISSUE TITLE
Required fields not handled

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#82]
**Describe the bug**
Whenever I try to add a snippet without adding any fields it gives an error failed to add snippet. A new user would not know which fields are required and which are optional .

**To Reproduce**
1. Go to 'Add Snippet'
2. Add in the details
3. Click on 'Add Snippet'

**Expected behavior**
If a user forgets to add any required filed it should display a message or warning to fill in the required fields.

**Screenshots**
![image](https://github.com/user-attachments/assets/ef5f8c87-70eb-4bb9-a4ce-100fa3cd4f5b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by inkerton** [comment]
@notsoocool  Assign the issue to me I would like to work on this one.

**Comment by inkerton** [comment]
i have a PR raised for delete snippet and I want to build edit snippet on top of those commit so till you merge my PR i will not be able to work on Edit snippet. So till then I would like to work on this one so assign it to me I have already started working on it and as soon as you checkout my delete snippet PR I will work on edit snippet simultaneously.

@notsoocool

**Comment by inkerton** [comment]
I will raise a PR for this till the end of the day.

**Comment by notsoocool** [comment]
I won't assign this issue to you for now, wait till the evening lemme the review your delete snippet first, then we will discuss about the edit snippet issue and this one after.

**Comment by inkerton** [comment]
@notsoocool Assign it to me also

**Comment by inkerton** [comment]
#39  I made a PR for it but u closed it stating this was not assigned to me. 

Assign it to me now I will reopen my old PR this will take less than 15 mins . @notsoocool This is now a stale issue nobody made a PR on it since then .

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/57362ce7-ae4d-4778-9aca-9daa4b2c978e)
![image](https://github.com/user-attachments/assets/73b9f4d0-6aa2-43d7-b0d7-9ce1c6e457c3)
![image](https://github.com/user-attachments/assets/a115fe9d-e675-4233-8022-0966da688c2b)
![image](https://github.com/user-attachments/assets/7a4ed0de-a38a-4578-aa35-d3fcc71896a2)
![image](https://github.com/user-attachments/assets/50f80d08-cab1-4197-9061-b677ccc8ee66)
![image](https://github.com/user-attachments/assets/8b0eb071-6d76-47c5-bb02-8fe2d23f4679)
![image](https://github.com/user-attachments/assets/3d40bae4-4783-4445-b010-27fafcf994df)
@notsoocool Done

**Comment by notsoocool** [comment]
> #39 I made a PR for it but u closed it stating this was not assigned to me.
> 
> Assign it to me now I will reopen my old PR this will take less than 15 mins . @notsoocool This is now a stale issue nobody made a PR on it since then .

@inkerton I will be opening new issues today. Feel free to comment on any of them if you'd like to be assigned. Thanks!
