### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [notsoocool/codecache#83]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@notsoocool Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by notsoocool** [comment]
@tarunkumar2005, I’d prefer not to have any GitHub Action workflows for now. I’ve had to disable them in the past because they haven’t been functioning as expected.

**Comment by tarunkumar2005** [comment]
I am saying on the website i will add contributors page we will use api not the action workflows @notsoocool

**Comment by notsoocool** [comment]
Oh, you're referring to the website. Let me think it over for a bit, and I’ll get back to you by the end of the day.

**Comment by tarunkumar2005** [comment]
Okay i have written website :- "Adding the contributors page to mention all the awersome people who have contributed to the website." you didn't read properly. no worries think about it whenever you are ready assign this to me i will work on this.

**Comment by notsoocool** [comment]
Thanks for clarifying, and I appreciate your patience, Tarun. I may have overlooked that detail in your message. I’ll take some time to review everything properly, and once I’m ready, I’ll be sure to assign this task to you. Thanks for your willingness to help!

**Comment by notsoocool** [comment]
You’re all set to work on this issue! Feel free to dive in, and let me know if you need any assistance or have questions along the way. I’m looking forward to seeing your progress!

**Comment by notsoocool** [comment]
Also a gentle reminder https://github.com/notsoocool/codecache/issues/91#issuecomment-2408902046
