### ISSUE TITLE
Navbar Design: Cramped Navigation Items and Small Search Bar

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [notsoocool/codecache#84]
# Navbar Design: Cramped Navigation Items and Small Search Bar

## Expected Behavior
- The navigation items should have adequate spacing between them for a clean, organized appearance.
- The search bar should be large enough for comfortable use and visibility.

## Current Behavior
- The spacing between navigation items (Home, Snippets, Add Snippet, Documentation) is minimal, causing a cramped appearance.
- The search bar appears smaller than expected, which may hinder usability.

## Steps to Reproduce
1. Open the web application.
2. Observe the navbar at the top of the page.
3. Notice the small gaps between navigation items.
4. Check the size of the search bar compared to the navigation items.

## Screenshots
 
![navbar](https://github.com/user-attachments/assets/a24dfc57-0c16-405f-b8a0-f98e9484daea)

## Environment
- **Browser**: [ 129.0.6668.101 ]
- **Operating System**: [ Windows 11]

 

## Labels
- Bug
- UI/UX
- gssoc-ext
- level1

**Comment by notsoocool** [comment]
Hey, thanks for the feedback! I actually prefer the original design of the navbar as it is. I think the current spacing and size work well for the layout I'm aiming for. Appreciate the suggestion though!
