### ISSUE TITLE
Missing Footer in Website Design

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [notsoocool/codecache#85]
# Missing Footer in Website Design

## Expected Behavior
- The website should have a footer to provide additional information, navigation links, and contact details, which enhances the user experience.

## Current Behavior
- The website currently lacks a footer, which may lead to a lack of information and navigation options at the bottom of the page.

## Steps to Reproduce
1. Open the web application.
2. Scroll to the bottom of any page.
3. Observe that there is no footer present.

## Screenshots
 
![footer](https://github.com/user-attachments/assets/1fbbb7b2-6689-418a-af57-b054d9505bbb)

## Possible Solutions
- Implement a footer that includes essential links, copyright information, and contact details.
- Consider adding social media links and a newsletter signup form for better user engagement.

## Environment
- **Browser**: [129.0.6668.1001 ]
- **Operating System**: [Windows 11]

## Additional Context
- A footer is a standard element in web design, providing users with essential information and a means to navigate back to key sections of the site.
- Adding a footer can also improve SEO by including additional links and keywords.

## Labels
- Feature Request
- UI/UX
- gssoc-ext
- level 1
- hacktoberfest-accepted

**Comment by notsoocool** [comment]
Thank you for pointing this out, @biswajit-sarkar-007 ! Adding a footer will indeed improve the user experience by providing additional navigation and contact information. You can go ahead and work on implementing this feature!

**Comment by notsoocool** [comment]
@biswajit-sarkar-007 
It’s been over a week without any update. Please let me know your progress, or I may need to reassign the issue.

Thanks!

**Comment by biswajit-sarkar-007** [comment]
@notsoocool, apologies for the delay. would you provided any additional details such as social media handles for your website that I could add, or any 'Contact Us' information like an email for the footer?

**Comment by Gauravtb2253** [comment]
Pls assign me
