### ISSUE TITLE
Add husky to the project

### ISSUE THREAD

**Issue by Ameerjafar** [notsoocool/codecache#87]
**Is your feature request related to a problem? Please describe.**
If Anyone try to commit their without the code formatting the husky will automatically format the changed code when their comes to commit their code.
This would really help the maintainer to review the code.

**Comment by Ameerjafar** [comment]
@notsoocool can you assign this issue to me to work on.

**Comment by notsoocool** [comment]
> **Is your feature request related to a problem? Please describe.** If Anyone try to commit their without the code formatting the husky will automatically format the changed code when their comes to commit their code. This would really help the maintainer to review the code.

Thanks for sharing your feature request! However, I'm having a bit of trouble understanding it. Could you please clarify what you're trying to say so I can better grasp the idea?

**Comment by Ameerjafar** [comment]
@notsoocool the husky thing will format code before the commit
