### ISSUE TITLE
Changing the twiiter logo to new X logo in documentation page

### ISSUE THREAD

**Issue by tarunkumar2005** [notsoocool/codecache#90]
![image](https://github.com/user-attachments/assets/f04a6484-61be-4f06-8515-faed56909597)

Changing the twiiter logo to new X logo in documentation page

@notsoocool Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by notsoocool** [comment]
We are not going to work on documentation page, as it is just a temporary page.
