### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website. (WEBSITE)

### ISSUE THREAD

**Issue by tarunkumar2005** [notsoocool/codecache#91]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@notsoocool Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by notsoocool** [comment]
Hi @tarunkumar2005 ,

I noticed that you've raised the same issue twice. I understand that communication can sometimes be frustrating, especially when waiting for a response. However, raising duplicate issues can clutter our workflow and make it harder to track problems effectively.

This serves as a warning for this instance. In the future, I kindly ask that you refrain from raising duplicate issues, as it may lead to action being taken on my part.

Thank you for your understanding, and I appreciate your contributions to the project.

**Comment by tarunkumar2005** [comment]
@notsoocool I am sorry for this i didn't saw that i raised this on two different days so i forgot i have already raised it that's why but i will keep this in mind next time so sorry for this.
