### ISSUE TITLE
Feature: Add Comment Section for Each Code Snippet

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [notsoocool/codecache#95]
#### **Description:**
It would be beneficial to add a **comment section** inside each code snippet where users can leave comments, ask questions, and discuss the snippet with other developers. This feature will promote collaboration and make CodeCache more interactive and community-driven.

#### **Feature Details:**
- **Comments per snippet**: Each snippet will have its own comment section, allowing users to discuss specific snippets.
- **User association**: Comments should display the username of the commenter.
- **Timestamp**: Each comment should display a timestamp of when it was posted.
- **Real-time updates**: Consider using web sockets or a similar mechanism for real-time comment updates without refreshing the page.

#### **Frontend Tasks:**
- Create a comment UI below each code snippet.
- Display each comment with the user's name, comment content, and timestamp.
- Add a text input for users to post comments, with a submit button.
- Include a placeholder when there are no comments (e.g., "Be the first to comment").

#### **Backend Tasks:**
- Define a **Comment** schema in MongoDB.
  - Fields: `snippetId`, `userId`, `commentText`, `timestamp`
- Set up a REST API mutation for creating, retrieving, and deleting comments.
- Ensure comments are linked to the appropriate snippet and user.

#### **Additional Considerations:**
- Comments should be stored in the database and loaded efficiently.
- UI should be responsive and intuitive.

![image](https://github.com/user-attachments/assets/bef3eae5-32d1-4748-8d38-0ecf4b4ac969)

- Comment section below the snippet

@notsoocool kindly assign this issue to me and add proper labels, thank you

**Comment by notsoocool** [comment]
@idk-mr4tyunjay 
Thank you for the suggestion! However, this feature was already added in #37 . Feel free to check it out and let us know if you have any other ideas or improvements!
