### ISSUE TITLE
COPYRIGHTS SECTION AT THE BOTTOM OF THE PAGE IS MISSING.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [notsoocool/codecache#98]
**Is your feature request related to a problem? Please describe.**
A COPYRIGHT SECTION IS NEEDED TO BE ADDED AT THE BOTTOM OF THE SCREEN FOR SECURITY REASONS.
PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

**Describe the solution you'd like**
Adding the section would make the page more professional.

**Comment by notsoocool** [comment]
@ABHISIKTAcommits Sure, feel free to add the copyright section. Please make sure not to change the design of the footer or alter the placement of any text. Thanks!
